### ISSUE TITLE
package.json cannot be found

### ISSUE THREAD

**Issue by 11mb** [venyii/hipchat-commander#4]
The installation instruction describes: "Add a new (global) integration to your HipChat account and use the following URL: <domain.tld>/package.json"

but the following error shows up:

[11-Jun-2016 10:43:39 UTC] PHP Fatal error:  Uncaught exception 'Assert\InvalidArgumentException' with message 'Array does not contain an element with key "packages"' in /vendor/beberlei/assert/lib/Assert/Assertion.php:209
Stack trace:
#0 /vendor/beberlei/assert/lib/Assert/Assertion.php(881): Assert\Assertion::createException(Array, 'Array does not ...', 26, NULL, Array)
#1 /src/HipChatCommander/Config/Config.php(92): Assert\Assertion::keyExists(Array, 'packages')
#2 /src/HipChatCommander/Config/Config.php(33): Venyii\HipChatCommander\Config\Config->validate()
#3 /src/HipChatCommander/Config/Config.php(186): Venyii\HipChatCommander\Config\Config->__construct(Array)
#4 /src/bootstrap.php(50): Venyii\HipChatCommander\Config\Config::loadYaml('bot_name: Estat...')
#5 /vendor/pimple/pimple/lib/Pimple.php(126): {closure}(Object(Silex\Application))
#6 /vendor/pimple/pimple/lib/Pimple.php(83): Si in /vendor/beberlei/assert/lib/Assert/Assertion.php on line 209

**Comment by 11mb** [comment]
Ah.. the packages array is required in the config.yml. Add this maybe to the config.yml.dist?

**Comment by venyii** [comment]
Thanks for the hint, I updated the `config.yml.dist` file in 80e2d47cfe85724a39b5cc05721ca57bf122f33e
